### ISSUE TITLE
Task list

### ISSUE THREAD

**Issue by JasonD94** [JasonD94/Dynamic-Ski-Maps#2]
1. Create image maps using GIMP / Photoshop for all 6 mountains:
- [x] Waterville Valley
- [x] Bretton Woods
- [x] Cannon Mt
- [x] Cranmore Mt
- [x] Pats Peak
- [x] Loon Mt

TODO:  @JohnShep, @HuyH0114, @BrendanBousquet 
1. Get JSON data from all 6 mountains.
2. [x] Waterville Valley
3. [x] Bretton Woods
4. [x] Cannon Mt
5. [x] Cranmore Mt
6. [x] Pats Peak
7. [x] Loon Mt

TODO: @JasonD94
- [x] Add Navigation bar to main homepage and all 6 Mt pages

TODO: @JohnShep, @HuyH0114, @BrendanBousquet, @JasonD94
- [ ] Fix mobile / desktop version (Bootstrap)

TODO: @JohnShep, @HuyH0114, @BrendanBousquet, @JasonD94
- [ ] Run site on AWS server, configure Python script to run on a set interval (hourly, daily, weekly?)

TODO: @JasonD94
- [ ] Continue testing, breaking the site and adding to the list of features / bug fixes / etc.

TODO: @JohnShep, @HuyH0114, @BrendanBousquet, @JasonD94
